In [7]:
# Import dependencies from Pandas, SKLearn, TensorFlow & MatPlotLib
from path import Path
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline

import sklearn as skl
from sklearn.datasets import make_blobs
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder,MinMaxScaler, LabelEncoder
from sklearn.svm import SVC

import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter(action='ignore', category=FutureWarning)

In [8]:
# Import Crime Data
crimes_df = pd.read_csv('doj_crime_info.csv')
crimes_df.head()

,Crimes - All Counties,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Violent Crimes,"210,492","210,510","207,988","204,591","197,432","189,593","194,128","191,493","185,233",...,"163,957","155,313","160,629","151,634","151,425","166,588","174,701","178,553","176,866","173,205"
1,Homicide,"2,074","2,201","2,392","2,402","2,394","2,503","2,483","2,258","2,143",...,"1,809","1,794","1,878","1,745","1,697","1,861","1,930","1,829","1,739","1,679"
2,Rape (Forcible Rape prior to 2014),"9,785","9,882","10,176","9,918","9,598","9,345","9,213","9,047","8,906",...,"8,325","7,678","7,828","7,459","9,397","12,793","13,695","14,724","15,500","14,720"
3,Rape,"8,197","8,219","8,620","8,461","8,287","8,115","7,937","7,931","7,859",...,"7,408","6,792","6,935","6,665","8,562","11,827","12,785","13,799","14,526","13,791"
4,Attempted Rape,"1,588","1,663","1,556","1,457","1,311","1,230","1,276","1,116","1,047",...,917,886,893,794,835,966,910,925,974,929

In [9]:
crimes_df

,Crimes - All Counties,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Violent Crimes,"210,492","210,510","207,988","204,591","197,432","189,593","194,128","191,493","185,233",...,"163,957","155,313","160,629","151,634","151,425","166,588","174,701","178,553","176,866","173,205"
1,Homicide,"2,074","2,201","2,392","2,402","2,394","2,503","2,483","2,258","2,143",...,"1,809","1,794","1,878","1,745","1,697","1,861","1,930","1,829","1,739","1,679"
2,Rape (Forcible Rape prior to 2014),"9,785","9,882","10,176","9,918","9,598","9,345","9,213","9,047","8,906",...,"8,325","7,678","7,828","7,459","9,397","12,793","13,695","14,724","15,500","14,720"
3,Rape,"8,197","8,219","8,620","8,461","8,287","8,115","7,937","7,931","7,859",...,"7,408","6,792","6,935","6,665","8,562","11,827","12,785","13,799","14,526","13,791"
4,Attempted Rape,"1,588","1,663","1,556","1,457","1,311","1,230","1,276","1,116","1,047",...,917,886,893,794,835,966,910,925,974,929
5,Robbery,"60,243","63,299","64,805","63,597","61,573","63,424","70,961","70,702","69,391",...,"58,100","54,358","56,491","53,621","48,650","52,785","54,769","56,609","54,312","52,050"
6,Firearm,"20,971","22,606","23,444","22,155","20,609","21,947","24,409","23,519","22,089",...,"18,076","16,180","17,083","16,274","13,546","14,706","15,490","15,349","13,501","12,414"
7,Knife or Cutting Instrument,"6,078","6,512","6,599","6,453","6,119","6,230","6,833","6,632","6,253",...,"5,051","4,817","4,920","4,641","4,553","5,028","5,207","5,277","5,031","4,719"
8,Other Weapon,"5,610","6,034","5,769","5,644","5,521","5,949","6,683","6,593","6,430",...,"5,361","4,907","5,259","5,089","4,818","5,651","6,067","6,502","6,538","6,068"
9,Strong-Arm,"27,584","28,147","28,993","29,345","29,324","29,298","33,036","33,958","34,619",...,"29,612","28,454","29,229","27,617","25,733","27,400","28,005","29,481","29,242","28,849"
10,Highway,"27,490","29,000","29,603","29,511","28,738","30,381","34,685","34,880","33,983",...,"28,360","26,302","26,246","24,463","22,052","22,872","22,953","22,494","21,231","19,782"
11,Commerical,"9,853","10,877","11,247","10,587","10,388","10,367","10,917","10,287","10,126",...,"8,463","8,231","8,608","8,191","7,871","9,567","10,187","11,134","10,771","10,429"
12,Gas Station,"1,608","1,721","1,678","1,522","1,458","1,665","1,689","1,596","1,477",...,"1,157","1,015","1,142","1,089",889,"1,257","1,263","1,453","1,480","1,286"
13,Convenience Store,"2,792","2,951","2,991","2,745","2,717","2,854","3,252","3,039","2,936",...,"2,476","2,210","2,547","2,264","2,385","2,845","3,062","3,453","3,369","3,188"
14,Residence,"5,278","5,333","5,489","5,349","5,046","5,142","5,512","5,674","5,848",...,"5,250","4,941","5,190","4,794","4,370","4,283","4,730","4,504","4,343","4,275"
15,Bank,"1,417","1,540","1,502","1,369","1,323","1,233","1,331","1,178","1,275",...,"1,029",916,845,784,696,662,669,596,568,443
16,Miscellaneous,"11,805","11,877","12,295","12,514","11,903","11,782","13,575","14,048","13,746",...,"11,365","10,743","11,913","12,036","10,387","11,299","11,905","12,975","12,550","12,647"
17,Aggravated Assault,"138,390","135,128","130,615","128,674","123,867","114,321","111,471","109,486","104,793",...,"95,723","91,483","94,432","88,809","91,681","99,149","104,307","105,391","105,315","104,756"
18,Firearm,"20,987","21,545","22,916","22,311","22,237","23,266","23,504","21,720","19,201",...,"16,971","17,164","18,040","15,610","15,801","18,286","20,633","19,157","17,908","17,748"
19,Knife or Cutting Instrument,"18,229","18,295","17,983","18,065","18,608","18,677","18,209","17,430","16,693",...,"15,182","14,873","15,128","14,504","14,859","17,100","17,157","17,123","16,936","16,413"
20,Other Weapon,"43,606","44,028","42,845","42,699","41,699","41,761","40,465","39,975","38,092",...,"33,092","30,732","31,533","30,008","32,481","33,985","36,048","36,579","36,494","35,093"
21,Hands Fists Feet,"55,568","51,260","46,871","45,599","41,323","30,617","29,293","30,361","30,807",...,"30,478","28,714","29,731","28,687","28,540","29,778","30,469","32,532","33,977","35,502"
22,Property Crimes,"1,054,860","1,120,487","1,171,644","1,209,030","1,223,275","1,195,381","1,156,010","1,112,366","1,081,272",...,"981,523","974,666","1,048,764","1,018,333","946,682","1,023,828","1,001,380","986,769","940,998","915,197"
23,Burglary,"222,247","229,922","237,445","240,705","244,914","249,563","246,449","237,759","237,988",...,"228,672","230,334","245,601","231,909","202,556","197,189","188,162","176,638","164,540","151,596"
24,Forcible Entry,"143,187","147,854","153,638","153,832","155,000","158,828","154,606","147,404","148,763",...,"143,186","144,761","153,439","145,363","124,169","126,654","123,642","119,074","111,649","104,958"
25,No Force,"79,060","82,068","83,807","86,873","89,914","90,735","91,843","90,355","89,225",...,"85,486","85,573","92,162","86,546","78,387","70,535","64,520","57,564","52,891","46,638"
26,Residence,"128,586","130,870","136,742","137,801","139,581","141,934","143,021","142,749","148,756",...,"149,112","151,184","160,815","147,240","125,136","120,297","108,783","95,942","85,693","72,710"
27,Night,"30,135","30,062","30,780","32,048","31,849","31,702","31,513","30,673","31,487",...,"32,441","32,471","34,480","32,907","27,437","28,013","26,696","24,399","22,266","20,228"
28,Day,"57,579","58,253","61,455","61,592","62,656","64,273","66,633","68,811","73,115",...,"73,984","75,836","79,974","72,242","58,052","54,561","47,537","40,216","35,334","29,479"
29,Unknown,"40,872","42,555","44,507","44,161","45,076","45,959","44,875","43,265","44,154",...,"42,687","42,877","46,361","42,091","39,647","37,723","34,550","31,327","28,093","23,003"
30,Non-Residence,"93,661","99,052","100,703","102,904","105,333","107,629","103,428","95,010","89,232",...,"79,560","79,150","84,786","84,669","77,420","76,892","79,379","80,696","78,847","78,886"
31,Night,"32,223","34,550","34,833","35,792","36,656","37,424","36,147","33,237","31,565",...,"30,083","29,601","32,407","32,965","29,884","31,295","34,465","35,781","35,459","35,715"
32,Day,"28,510","28,323","28,253","29,606","30,570","30,604","30,219","28,926","27,505",...,"25,884","26,015","27,849","27,529","24,182","20,999","20,504","20,366","20,360","20,888"
33,Unknown,"32,928","36,179","37,617","37,506","38,107","39,601","37,062","32,847","30,162",...,"23,593","23,534","24,530","24,175","23,354","24,598","24,410","24,549","23,028","22,283"
34,Motor Vehicle Theft,"181,049","201,074","221,780","240,798","251,747","256,998","242,692","220,126","192,631",...,"152,494","147,030","168,516","165,217","151,790","170,788","176,676","168,327","155,170","140,732"
35,Automotive,"130,656","145,980","162,478","180,451","188,311","193,183","182,658","167,250","144,289",...,"117,653","113,534","132,230","128,370","120,088","136,119","138,391","123,726","110,141","98,110"
36,Trucks and Buses,"40,982","44,713","47,550","46,741","48,262","48,209","45,419","40,219","36,194",...,"24,984","23,446","25,284","25,145","21,816","23,365","26,040","32,127","33,524","31,303"
37,Other,"9,411","10,381","11,752","13,606","15,174","15,606","14,615","12,657","12,148",...,"9,857","10,050","11,002","11,702","9,886","11,304","12,245","12,474","11,505","11,319"
38,Larceny-Theft,"651,564","689,491","712,419","727,527","726,614","688,820","666,869","654,481","650,653",...,"600,357","597,302","634,647","621,207","592,336","655,851","636,542","641,804","621,288","622,869"
39,Pocket-Picking,"4,523","3,316","3,788","3,864","3,509","3,274","3,384","3,791","3,556",...,"3,186","3,281","3,431","3,478","3,293","3,783","3,903","4,874","5,228","6,033"
40,Purse-Snatching,"4,502","4,524","4,234","4,507","4,291","4,125","4,513","4,100","3,798",...,"3,181","2,857","2,851","2,863","2,706","2,790","2,472","2,599","2,312","2,444"
41,Shoplifting,"89,908","88,330","90,597","93,086","93,482","86,364","82,775","88,412","94,891",...,"93,665","91,845","94,136","93,532","97,301","108,659","98,589","91,553","89,378","90,309"
42,From Motor Vehicle,"223,309","245,033","270,230","282,126","280,665","272,073","266,186","256,636","247,270",...,"225,416","211,903","223,295","217,029","202,916","235,419","238,185","256,625","243,040","245,795"
43,Motor Vehicle Accessories,"61,913","74,605","78,528","80,734","82,037","73,035","64,615","57,762","59,324",...,"49,609","46,924","49,277","46,320","48,029","53,541","51,656","51,897","51,872","55,209"
44,Bicycles,"29,535","27,931","26,474","26,605","25,231","23,244","21,041","20,074","22,680",...,"26,445","30,093","35,159","34,747","33,095","36,554","31,739","28,996","27,336","24,494"
45,From Building,"104,243","109,345","106,359","101,445","99,960","93,578","89,171","85,268","81,371",...,"75,313","76,803","80,634","77,017","80,294","77,023","72,225","69,892","69,324","66,657"
46,Coin Operated Machine,"5,255","5,629","3,636","3,455","3,342","3,306","2,519","2,394","2,153",...,"1,634","1,414","1,450","1,599","1,230","1,307","1,468","1,406","1,037","1,055"
47,Other,"128,376","130,778","128,573","131,705","134,097","129,821","132,665","136,044","135,610",...,"121,908","132,182","144,414","144,622","123,472","136,775","136,305","133,962","131,761","130,873"
48,Over $400,"175,013","195,037","208,367","211,634","215,532","215,772","218,466","223,350","226,125",...,"203,833","216,030","232,014","228,035","215,820","238,456","235,543","261,346","270,124","281,436"
49,$200 through $400,"102,424","106,602","110,107","113,392","114,873","109,155","105,213","102,009","102,947",...,"96,180","91,666","95,880","90,476","85,033","91,947","86,853","86,436","84,523","82,438"
50,$50 through $199,"138,102","144,146","143,798","146,475","145,082","133,188","123,996","118,991","118,202",...,"115,484","113,113","118,159","112,284","110,108","120,590","112,408","108,836","105,185","100,697"
51,Under $50,"236,025","243,706","250,147","256,026","251,127","230,705","219,194","210,131","203,379",...,"184,860","176,493","188,594","190,412","181,375","204,858","201,738","185,186","161,456","158,298"
52,Arson,"14,406","15,060","14,007","13,677","12,660","12,272","12,687","11,400","10,674",...,"7,864","7,164","7,519","7,446","7,135","7,380","7,766","8,650","8,523","8,266"
53,Structural Property,"4,669","4,612","4,119","3,992","3,786","3,774","3,758","3,438","3,416",...,"2,546","2,327","2,654","2,528","2,459","2,450","2,805","3,175","2,825","2,877"
54,Mobile Property,"4,616","5,357","5,473","5,419","4,846","4,349","4,442","4,011","3,888",...,"2,501","2,060","1,978","1,822","1,825","1,853","1,943","1,979","2,047","1,773"
55,Other Property,"5,121","5,091","4,415","4,266","4,028","4,149","4,487","3,951","3,370",...,"2,817","2,777","2,887","3,096","2,851","3,077","3,018","3,496","3,651","3,616"

In [10]:
# Import COVID Data
covid_df = pd.read_csv('us-county-health-rankings-2020.csv')
covid_df.head()

,fips,state,county,num_deaths,years_of_potential_life_lost_rate,95percent_ci_low,95percent_ci_high,quartile,ypll_rate_aian,ypll_rate_aian_95percent_ci_low,...,percent_hispanic,num_non_hispanic_white,percent_non_hispanic_white,num_not_proficient_in_english,percent_not_proficient_in_english,95percent_ci_low_39,95percent_ci_high_39,percent_female,num_rural,percent_rural
0,1000,Alabama,NaN,81791.0,9942.794666,9840.535949,10045.053384,NaN,NaN,NaN,...,4.443264,3197324,65.413428,48517,1.061048,1.006759,1.115337,51.633032,1957932.0,40.963183
1,1001,Alabama,Autauga,791.0,8128.591190,7283.340731,8973.841649,1.0,NaN,NaN,...,2.965774,41316,74.308016,426,0.820225,0.347891,1.292558,51.448715,22921.0,42.002162
2,1003,Alabama,Baldwin,2967.0,7354.122530,6918.554269,7789.690790,1.0,NaN,NaN,...,4.646779,181201,83.111337,1068,0.543517,0.347271,0.739763,51.538377,77060.0,42.279099
3,1005,Alabama,Barbour,472.0,10253.573403,8782.217281,11724.929524,2.0,NaN,NaN,...,4.276355,11356,45.641252,398,1.631683,0.824903,2.438462,47.216752,18613.0,67.789635
4,1007,Alabama,Bibb,471.0,11977.539484,10344.064842,13611.014126,3.0,NaN,NaN,...,2.625000,16708,74.589286,57,0.268210,0.000000,0.807504,46.781250,15663.0,68.352607

In [11]:
covid_df

,fips,state,county,num_deaths,years_of_potential_life_lost_rate,95percent_ci_low,95percent_ci_high,quartile,ypll_rate_aian,ypll_rate_aian_95percent_ci_low,...,percent_hispanic,num_non_hispanic_white,percent_non_hispanic_white,num_not_proficient_in_english,percent_not_proficient_in_english,95percent_ci_low_39,95percent_ci_high_39,percent_female,num_rural,percent_rural
0,1000,Alabama,NaN,81791.0,9942.794666,9840.535949,10045.053384,NaN,NaN,NaN,...,4.443264,3197324,65.413428,48517,1.061048,1.006759,1.115337,51.633032,1957932.0,40.963183
1,1001,Alabama,Autauga,791.0,8128.591190,7283.340731,8973.841649,1.0,NaN,NaN,...,2.965774,41316,74.308016,426,0.820225,0.347891,1.292558,51.448715,22921.0,42.002162
2,1003,Alabama,Baldwin,2967.0,7354.122530,6918.554269,7789.690790,1.0,NaN,NaN,...,4.646779,181201,83.111337,1068,0.543517,0.347271,0.739763,51.538377,77060.0,42.279099
3,1005,Alabama,Barbour,472.0,10253.573403,8782.217281,11724.929524,2.0,NaN,NaN,...,4.276355,11356,45.641252,398,1.631683,0.824903,2.438462,47.216752,18613.0,67.789635
4,1007,Alabama,Bibb,471.0,11977.539484,10344.064842,13611.014126,3.0,NaN,NaN,...,2.625000,16708,74.589286,57,0.268210,0.000000,0.807504,46.781250,15663.0,68.352607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,56037,Wyoming,Sweetwater,532.0,7831.827655,6915.944384,8747.710925,4.0,NaN,NaN,...,16.083250,34145,79.312908,669,1.633221,0.993813,2.272629,48.544749,4782.0,10.916313
3189,56039,Wyoming,Teton,109.0,2730.603992,1991.644111,3469.563872,1.0,NaN,NaN,...,14.878038,18812,81.504268,945,4.314477,2.787340,5.841615,48.403449,9887.0,46.430920
3190,56041,Wyoming,Uinta,256.0,7330.683549,6011.148684,8650.218415,3.0,NaN,NaN,...,9.236908,17741,87.398394,133,0.696080,0.000000,1.429709,49.332479,9101.0,43.095937
3191,56043,Wyoming,Washakie,110.0,6586.049959,4500.924119,8671.175799,2.0,NaN,NaN,...,14.051997,6498,82.409639,25,0.324886,0.000000,1.376766,49.422955,3068.0,35.954529
3192,56045,Wyoming,Weston,89.0,5388.706947,3608.901615,7739.082057,1.0,NaN,NaN,...,4.076360,6267,89.952634,58,0.862069,0.000000,2.255604,47.050380,3931.0,54.536626

In [14]:
covid_df.describe()

,fips,num_deaths,years_of_potential_life_lost_rate,95percent_ci_low,95percent_ci_high,quartile,ypll_rate_aian,ypll_rate_aian_95percent_ci_low,ypll_rate_aian_95percent_ci_high,ypll_rate_asian,...,percent_hispanic,num_non_hispanic_white,percent_non_hispanic_white,num_not_proficient_in_english,percent_not_proficient_in_english,95percent_ci_low_39,95percent_ci_high_39,percent_female,num_rural,percent_rural
count,3193.000000,2900.000000,2900.000000,2900.000000,2900.000000,3084.000000,175.000000,175.000000,175.000000,224.000000,...,3193.000000,3.193000e+03,3193.000000,3.193000e+03,3193.000000,3038.000000,3038.000000,3193.000000,3.186000e+03,3186.000000
mean,30360.922643,2626.418621,8560.596542,7231.352606,9935.234974,2.460441,14948.402184,11322.604297,19263.626656,3494.138600,...,9.692285,1.237372e+05,75.863247,8.345050e+03,1.717440,1.066770,2.649472,49.896722,3.733560e+04,58.058842
std,15171.912105,14147.013596,2593.841317,2225.987099,3191.809731,1.117515,5786.739134,4618.356203,7553.456260,1339.897189,...,13.790012,6.538542e+05,20.159411,8.751863e+04,2.779003,2.270823,3.801944,2.269008,1.839409e+05,31.552734
min,1000.000000,32.000000,2730.603992,1991.644111,3018.828260,1.000000,3182.709083,2161.351633,4386.945226,1422.108274,...,0.610451,2.300000e+01,2.691288,0.000000e+00,0.000000,0.000000,0.236579,26.835097,0.000000e+00,0.000000
25%,18173.000000,228.000000,6769.680562,5653.284707,7715.584748,1.000000,10760.588056,7888.395153,14151.672287,2572.251914,...,2.408442,8.043000e+03,63.959619,4.200000e+01,0.286138,0.000000,0.892524,49.422955,7.144000e+03,32.560275
50%,29175.000000,487.500000,8287.134501,7009.538366,9583.009259,2.000000,14238.200703,11098.411681,18116.802008,3199.857322,...,4.456522,2.056000e+04,83.063727,1.840000e+02,0.741392,0.169443,1.492338,50.313328,1.470750e+04,58.841080
75%,45075.000000,1187.000000,10052.108422,8612.066274,11755.851732,3.000000,17819.011123,13519.826184,22614.952183,4045.810688,...,10.209401,5.713900e+04,92.178182,9.680000e+02,1.897017,1.109426,2.817192,51.028709,2.623375e+04,86.187079
max,56045.000000,347916.000000,29138.378057,25269.174532,39386.622280,5.000000,32929.263642,27177.548936,45412.859692,9710.756786,...,96.359551,1.456861e+07,97.887219,3.597443e+06,30.376303,23.549746,80.322576,56.870539,3.847522e+06,100.000000